job_types:
  - java developer
  - backend
  - software engineer

skills:
  must_have:
    - java
    - spring
    - api
  nice_to_have:
    - docker
    - aws
    - typescript
    - nextjs

locations:
  remote: true
  countries:
    - Finland
    - Sweden
    - Norway
    - Denmark
    - Estonia
  exclude_regions: []

experience_level:
  - mid
  - senior

min_salary: 60000

keywords:
  - remote
  - backend
  - java
  - spring
  - spring boot
  - hibernate

excluded_terms:
  - wordpress
  - php
  - junior

company_types:
  - startup
  - tech
  - established

scoring:
  skill_match_weight: 0.4
  location_weight: 0.2
  salary_weight: 0.2
  company_weight: 0.1
  job_description_weight: 0.1

notification:
  min_score: 0.5
  daily_limit: 5
